HOST: gpu[11-14]
CP_FILE_NAME: small
HOST: gpu[11-14]
CUDA_VISIBLE_DEVICES: 
GPU_NUM: 32
PROC_NUM: 32
NNODES: 4
NTASK_PER_NODE: 8
+ srun -p Nvidia_A800 -N 4 --ntasks-per-node 8 --gres=gpu:8 --mem 256G -K -w 'gpu[11-14]' ./scripts/executor.sh python conflict_bench.py --backend NCCL --config ./scripts/configs/small_32.json
srun: job 116525 queued and waiting for resources
srun: job 116525 has been allocated resources
[INFO]: Cluster init done !!!
Traceback (most recent call last):
  File "conflict_bench.py", line 167, in <module>
    main()
  File "conflict_bench.py", line 101, in main
    patterns = json.load(f)
  File "/public/home/qinghuatest/miniconda3/envs/yhy_mg/lib/python3.8/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/public/home/qinghuatest/miniconda3/envs/yhy_mg/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/public/home/qinghuatest/miniconda3/envs/yhy_mg/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/public/home/qinghuatest/miniconda3/envs/yhy_mg/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 5 column 47 (char 118)
Traceback (most recent call last):
  File "conflict_bench.py", line 167, in <module>
    main()
  File "conflict_bench.py", line 101, in main
    patterns = json.load(f)
  File "/public/home/qinghuatest/miniconda3/envs/yhy_mg/lib/python3.8/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/public/home/qinghuatest/miniconda3/envs/yhy_mg/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/public/home/qinghuatest/miniconda3/envs/yhy_mg/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/public/home/qinghuatest/miniconda3/envs/yhy_mg/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 5 column 47 (char 118)
Traceback (most recent call last):
  File "conflict_bench.py", line 167, in <module>
    main()
  File "conflict_bench.py", line 101, in main
    patterns = json.load(f)
  File "/public/home/qinghuatest/miniconda3/envs/yhy_mg/lib/python3.8/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/public/home/qinghuatest/miniconda3/envs/yhy_mg/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/public/home/qinghuatest/miniconda3/envs/yhy_mg/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/public/home/qinghuatest/miniconda3/envs/yhy_mg/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 5 column 47 (char 118)
Traceback (most recent call last):
  File "conflict_bench.py", line 167, in <module>
    main()
  File "conflict_bench.py", line 101, in main
    patterns = json.load(f)
  File "/public/home/qinghuatest/miniconda3/envs/yhy_mg/lib/python3.8/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/public/home/qinghuatest/miniconda3/envs/yhy_mg/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/public/home/qinghuatest/miniconda3/envs/yhy_mg/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/public/home/qinghuatest/miniconda3/envs/yhy_mg/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 5 column 47 (char 118)
Traceback (most recent call last):
  File "conflict_bench.py", line 167, in <module>
    main()
  File "conflict_bench.py", line 101, in main
    patterns = json.load(f)
  File "/public/home/qinghuatest/miniconda3/envs/yhy_mg/lib/python3.8/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/public/home/qinghuatest/miniconda3/envs/yhy_mg/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/public/home/qinghuatest/miniconda3/envs/yhy_mg/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/public/home/qinghuatest/miniconda3/envs/yhy_mg/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 5 column 47 (char 118)
Traceback (most recent call last):
  File "conflict_bench.py", line 167, in <module>
    main()
  File "conflict_bench.py", line 101, in main
    patterns = json.load(f)
  File "/public/home/qinghuatest/miniconda3/envs/yhy_mg/lib/python3.8/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/public/home/qinghuatest/miniconda3/envs/yhy_mg/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/public/home/qinghuatest/miniconda3/envs/yhy_mg/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/public/home/qinghuatest/miniconda3/envs/yhy_mg/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 5 column 47 (char 118)
Traceback (most recent call last):
  File "conflict_bench.py", line 167, in <module>
    main()
  File "conflict_bench.py", line 101, in main
    patterns = json.load(f)
  File "/public/home/qinghuatest/miniconda3/envs/yhy_mg/lib/python3.8/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/public/home/qinghuatest/miniconda3/envs/yhy_mg/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/public/home/qinghuatest/miniconda3/envs/yhy_mg/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/public/home/qinghuatest/miniconda3/envs/yhy_mg/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 5 column 47 (char 118)
Traceback (most recent call last):
  File "conflict_bench.py", line 167, in <module>
    main()
  File "conflict_bench.py", line 101, in main
    patterns = json.load(f)
  File "/public/home/qinghuatest/miniconda3/envs/yhy_mg/lib/python3.8/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/public/home/qinghuatest/miniconda3/envs/yhy_mg/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/public/home/qinghuatest/miniconda3/envs/yhy_mg/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/public/home/qinghuatest/miniconda3/envs/yhy_mg/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 5 column 47 (char 118)
Traceback (most recent call last):
  File "conflict_bench.py", line 167, in <module>
    main()
  File "conflict_bench.py", line 101, in main
    patterns = json.load(f)
  File "/public/home/qinghuatest/miniconda3/envs/yhy_mg/lib/python3.8/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/public/home/qinghuatest/miniconda3/envs/yhy_mg/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/public/home/qinghuatest/miniconda3/envs/yhy_mg/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/public/home/qinghuatest/miniconda3/envs/yhy_mg/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 5 column 47 (char 118)
Traceback (most recent call last):
  File "conflict_bench.py", line 167, in <module>
    main()
  File "conflict_bench.py", line 101, in main
    patterns = json.load(f)
  File "/public/home/qinghuatest/miniconda3/envs/yhy_mg/lib/python3.8/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/public/home/qinghuatest/miniconda3/envs/yhy_mg/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/public/home/qinghuatest/miniconda3/envs/yhy_mg/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/public/home/qinghuatest/miniconda3/envs/yhy_mg/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 5 column 47 (char 118)
Traceback (most recent call last):
  File "conflict_bench.py", line 167, in <module>
    main()
  File "conflict_bench.py", line 101, in main
    patterns = json.load(f)
  File "/public/home/qinghuatest/miniconda3/envs/yhy_mg/lib/python3.8/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/public/home/qinghuatest/miniconda3/envs/yhy_mg/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/public/home/qinghuatest/miniconda3/envs/yhy_mg/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/public/home/qinghuatest/miniconda3/envs/yhy_mg/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 5 column 47 (char 118)
Traceback (most recent call last):
  File "conflict_bench.py", line 167, in <module>
    main()
  File "conflict_bench.py", line 101, in main
    patterns = json.load(f)
  File "/public/home/qinghuatest/miniconda3/envs/yhy_mg/lib/python3.8/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/public/home/qinghuatest/miniconda3/envs/yhy_mg/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/public/home/qinghuatest/miniconda3/envs/yhy_mg/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/public/home/qinghuatest/miniconda3/envs/yhy_mg/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 5 column 47 (char 118)
Traceback (most recent call last):
  File "conflict_bench.py", line 167, in <module>
    main()
  File "conflict_bench.py", line 101, in main
    patterns = json.load(f)
  File "/public/home/qinghuatest/miniconda3/envs/yhy_mg/lib/python3.8/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/public/home/qinghuatest/miniconda3/envs/yhy_mg/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/public/home/qinghuatest/miniconda3/envs/yhy_mg/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/public/home/qinghuatest/miniconda3/envs/yhy_mg/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 5 column 47 (char 118)
Traceback (most recent call last):
  File "conflict_bench.py", line 167, in <module>
    main()
  File "conflict_bench.py", line 101, in main
    patterns = json.load(f)
  File "/public/home/qinghuatest/miniconda3/envs/yhy_mg/lib/python3.8/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/public/home/qinghuatest/miniconda3/envs/yhy_mg/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/public/home/qinghuatest/miniconda3/envs/yhy_mg/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/public/home/qinghuatest/miniconda3/envs/yhy_mg/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 5 column 47 (char 118)
Traceback (most recent call last):
  File "conflict_bench.py", line 167, in <module>
    main()
  File "conflict_bench.py", line 101, in main
    patterns = json.load(f)
  File "/public/home/qinghuatest/miniconda3/envs/yhy_mg/lib/python3.8/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/public/home/qinghuatest/miniconda3/envs/yhy_mg/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/public/home/qinghuatest/miniconda3/envs/yhy_mg/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/public/home/qinghuatest/miniconda3/envs/yhy_mg/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 5 column 47 (char 118)
Traceback (most recent call last):
  File "conflict_bench.py", line 167, in <module>
    main()
  File "conflict_bench.py", line 101, in main
    patterns = json.load(f)
  File "/public/home/qinghuatest/miniconda3/envs/yhy_mg/lib/python3.8/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/public/home/qinghuatest/miniconda3/envs/yhy_mg/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/public/home/qinghuatest/miniconda3/envs/yhy_mg/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/public/home/qinghuatest/miniconda3/envs/yhy_mg/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 5 column 47 (char 118)
Traceback (most recent call last):
  File "conflict_bench.py", line 167, in <module>
    main()
  File "conflict_bench.py", line 101, in main
    patterns = json.load(f)
  File "/public/home/qinghuatest/miniconda3/envs/yhy_mg/lib/python3.8/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/public/home/qinghuatest/miniconda3/envs/yhy_mg/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/public/home/qinghuatest/miniconda3/envs/yhy_mg/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/public/home/qinghuatest/miniconda3/envs/yhy_mg/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 5 column 47 (char 118)
Traceback (most recent call last):
  File "conflict_bench.py", line 167, in <module>
    main()
  File "conflict_bench.py", line 101, in main
    patterns = json.load(f)
  File "/public/home/qinghuatest/miniconda3/envs/yhy_mg/lib/python3.8/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/public/home/qinghuatest/miniconda3/envs/yhy_mg/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/public/home/qinghuatest/miniconda3/envs/yhy_mg/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/public/home/qinghuatest/miniconda3/envs/yhy_mg/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 5 column 47 (char 118)
Traceback (most recent call last):
  File "conflict_bench.py", line 167, in <module>
    main()
  File "conflict_bench.py", line 101, in main
    patterns = json.load(f)
  File "/public/home/qinghuatest/miniconda3/envs/yhy_mg/lib/python3.8/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/public/home/qinghuatest/miniconda3/envs/yhy_mg/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/public/home/qinghuatest/miniconda3/envs/yhy_mg/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/public/home/qinghuatest/miniconda3/envs/yhy_mg/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 5 column 47 (char 118)
Traceback (most recent call last):
  File "conflict_bench.py", line 167, in <module>
    main()
  File "conflict_bench.py", line 101, in main
    patterns = json.load(f)
  File "/public/home/qinghuatest/miniconda3/envs/yhy_mg/lib/python3.8/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/public/home/qinghuatest/miniconda3/envs/yhy_mg/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/public/home/qinghuatest/miniconda3/envs/yhy_mg/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/public/home/qinghuatest/miniconda3/envs/yhy_mg/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 5 column 47 (char 118)
Traceback (most recent call last):
  File "conflict_bench.py", line 167, in <module>
    main()
  File "conflict_bench.py", line 101, in main
    patterns = json.load(f)
  File "/public/home/qinghuatest/miniconda3/envs/yhy_mg/lib/python3.8/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/public/home/qinghuatest/miniconda3/envs/yhy_mg/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/public/home/qinghuatest/miniconda3/envs/yhy_mg/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/public/home/qinghuatest/miniconda3/envs/yhy_mg/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 5 column 47 (char 118)
Traceback (most recent call last):
  File "conflict_bench.py", line 167, in <module>
    main()
  File "conflict_bench.py", line 101, in main
    patterns = json.load(f)
  File "/public/home/qinghuatest/miniconda3/envs/yhy_mg/lib/python3.8/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/public/home/qinghuatest/miniconda3/envs/yhy_mg/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/public/home/qinghuatest/miniconda3/envs/yhy_mg/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/public/home/qinghuatest/miniconda3/envs/yhy_mg/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 5 column 47 (char 118)
Traceback (most recent call last):
  File "conflict_bench.py", line 167, in <module>
    main()
  File "conflict_bench.py", line 101, in main
    patterns = json.load(f)
  File "/public/home/qinghuatest/miniconda3/envs/yhy_mg/lib/python3.8/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/public/home/qinghuatest/miniconda3/envs/yhy_mg/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/public/home/qinghuatest/miniconda3/envs/yhy_mg/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/public/home/qinghuatest/miniconda3/envs/yhy_mg/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 5 column 47 (char 118)
Traceback (most recent call last):
  File "conflict_bench.py", line 167, in <module>
    main()
  File "conflict_bench.py", line 101, in main
    patterns = json.load(f)
  File "/public/home/qinghuatest/miniconda3/envs/yhy_mg/lib/python3.8/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/public/home/qinghuatest/miniconda3/envs/yhy_mg/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/public/home/qinghuatest/miniconda3/envs/yhy_mg/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/public/home/qinghuatest/miniconda3/envs/yhy_mg/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 5 column 47 (char 118)
Traceback (most recent call last):
  File "conflict_bench.py", line 167, in <module>
    main()
  File "conflict_bench.py", line 101, in main
    patterns = json.load(f)
  File "/public/home/qinghuatest/miniconda3/envs/yhy_mg/lib/python3.8/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/public/home/qinghuatest/miniconda3/envs/yhy_mg/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/public/home/qinghuatest/miniconda3/envs/yhy_mg/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/public/home/qinghuatest/miniconda3/envs/yhy_mg/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 5 column 47 (char 118)
Traceback (most recent call last):
  File "conflict_bench.py", line 167, in <module>
    main()
  File "conflict_bench.py", line 101, in main
    patterns = json.load(f)
  File "/public/home/qinghuatest/miniconda3/envs/yhy_mg/lib/python3.8/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/public/home/qinghuatest/miniconda3/envs/yhy_mg/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/public/home/qinghuatest/miniconda3/envs/yhy_mg/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/public/home/qinghuatest/miniconda3/envs/yhy_mg/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 5 column 47 (char 118)
Traceback (most recent call last):
  File "conflict_bench.py", line 167, in <module>
    main()
  File "conflict_bench.py", line 101, in main
    patterns = json.load(f)
  File "/public/home/qinghuatest/miniconda3/envs/yhy_mg/lib/python3.8/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/public/home/qinghuatest/miniconda3/envs/yhy_mg/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/public/home/qinghuatest/miniconda3/envs/yhy_mg/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/public/home/qinghuatest/miniconda3/envs/yhy_mg/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 5 column 47 (char 118)
Traceback (most recent call last):
  File "conflict_bench.py", line 167, in <module>
    main()
  File "conflict_bench.py", line 101, in main
    patterns = json.load(f)
  File "/public/home/qinghuatest/miniconda3/envs/yhy_mg/lib/python3.8/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/public/home/qinghuatest/miniconda3/envs/yhy_mg/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/public/home/qinghuatest/miniconda3/envs/yhy_mg/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/public/home/qinghuatest/miniconda3/envs/yhy_mg/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 5 column 47 (char 118)
Traceback (most recent call last):
  File "conflict_bench.py", line 167, in <module>
    main()
  File "conflict_bench.py", line 101, in main
    patterns = json.load(f)
  File "/public/home/qinghuatest/miniconda3/envs/yhy_mg/lib/python3.8/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/public/home/qinghuatest/miniconda3/envs/yhy_mg/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/public/home/qinghuatest/miniconda3/envs/yhy_mg/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/public/home/qinghuatest/miniconda3/envs/yhy_mg/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 5 column 47 (char 118)
Traceback (most recent call last):
  File "conflict_bench.py", line 167, in <module>
    main()
  File "conflict_bench.py", line 101, in main
    patterns = json.load(f)
  File "/public/home/qinghuatest/miniconda3/envs/yhy_mg/lib/python3.8/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/public/home/qinghuatest/miniconda3/envs/yhy_mg/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/public/home/qinghuatest/miniconda3/envs/yhy_mg/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/public/home/qinghuatest/miniconda3/envs/yhy_mg/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 5 column 47 (char 118)
Traceback (most recent call last):
  File "conflict_bench.py", line 167, in <module>
    main()
  File "conflict_bench.py", line 101, in main
    patterns = json.load(f)
  File "/public/home/qinghuatest/miniconda3/envs/yhy_mg/lib/python3.8/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/public/home/qinghuatest/miniconda3/envs/yhy_mg/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/public/home/qinghuatest/miniconda3/envs/yhy_mg/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/public/home/qinghuatest/miniconda3/envs/yhy_mg/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 5 column 47 (char 118)
Traceback (most recent call last):
  File "conflict_bench.py", line 167, in <module>
    main()
  File "conflict_bench.py", line 101, in main
    patterns = json.load(f)
  File "/public/home/qinghuatest/miniconda3/envs/yhy_mg/lib/python3.8/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/public/home/qinghuatest/miniconda3/envs/yhy_mg/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/public/home/qinghuatest/miniconda3/envs/yhy_mg/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/public/home/qinghuatest/miniconda3/envs/yhy_mg/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 5 column 47 (char 118)
srun: error: gpu14: tasks 24,26,31: Exited with exit code 1
srun: launch/slurm: _step_signal: Terminating StepId=116525.0
slurmstepd: error: *** STEP 116525.0 ON gpu11 CANCELLED AT 2024-06-04T04:39:48 ***
srun: error: gpu13: tasks 16,20,23: Exited with exit code 1
srun: error: gpu12: tasks 9,11,14: Exited with exit code 1
srun: error: gpu11: tasks 0-1,6: Exited with exit code 1
srun: error: gpu14: tasks 27-28,30: Exited with exit code 1
srun: error: gpu11: tasks 2,4,7: Exited with exit code 1
srun: error: gpu12: tasks 12-13,15: Exited with exit code 1
srun: error: gpu13: tasks 17-18,22: Exited with exit code 1
srun: error: gpu14: task 29: Exited with exit code 1
srun: error: gpu12: task 8: Exited with exit code 1
srun: error: gpu11: task 3: Exited with exit code 1
srun: error: gpu13: task 21: Exited with exit code 1
srun: error: gpu14: task 25: Exited with exit code 1
srun: error: gpu11: task 5: Exited with exit code 1
srun: error: gpu13: task 19: Exited with exit code 1
srun: error: gpu12: task 10: Exited with exit code 1
